### ISSUE TITLE
Do you think this could make modern shaders for the upbge project?

### ISSUE THREAD

**Issue by BluePrintRandom** [victorfisac/FNode#5]
Do you think this could make modern shaders for the upbge project?

could you help us replace the current GLSL node editor with your system?

can this also build 2d filters?
https://github.com/UPBGE/blender

**Comment by victorfisac** [comment]
This tool lets the developer to create any types of shaders; but it's focused in raylib shaders nomenclature.

You can create shaders and then apply them to a 3D drawing mesh or a 2D filter applied to a RenderToTexture.
